name: Download Vigilance Image

on:
  schedule:
    - cron: '0 * * * *' # toutes les heures
  workflow_dispatch: # permet de lancer manuellement

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Télécharger la carte de vigilance
        run: |
          curl -o public/vigilance.png https://vigilance.meteofrance.re/reunion/vigilance/images/vigilance.png

      - name: Commit et push si modification
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add public/vigilance.png
          git commit -m "Mise à jour automatique de la carte de vigilance" || echo "Pas de changements"
          git push
