- name: Commit et push si modification
  run: |
    git config user.name "GitHub Actions"
    git config user.email "actions@github.com"
    git add public/vigilance.png

    if git diff --cached --quiet; then
      echo "Aucun changement à committer"
    else
      git commit -m "Mise à jour automatique de la carte de vigilance"
      git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
    fi
