name: Mise à jour vigilance

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *' # tous les jours à 4h UTC (8h La Réunion)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Cloner le dépôt
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Configurer Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Installer les dépendances
      run: |
        sudo apt-get update
        sudo apt-get install -y poppler-utils
        pip install requests

    - name: Exécuter le script Python
      run: python public/update_vigilance.py

    - name: Ajouter et commit si changement
      run: |
        git add public/vigilance.png
        git diff --cached --quiet || git commit -m "Mise à jour automatique de l'image de vigilance"

    - name: Pousser les changements
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
