name: update_vigilance

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * *'  # Tous les jours à 4h UTC (8h à La Réunion)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer Poppler
        run: sudo apt-get update && sudo apt-get install -y poppler-utils

      - name: Installer les dépendances Python
        run: pip install -r requirements.txt

      - name: Exécuter le script Python
        run: python public/update_vigilance.py

      - name: Commit si fichier modifié
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add public/
          if ! git diff --quiet --cached; then
            git commit -m "Mise à jour image vigilance"
            git push
          else
            echo "Aucun changement à pousser."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
