name: Mise à jour Vigilance Réunion

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * *'  # tous les jours à 5h UTC (9h Réunion)

jobs:
  update_vigilance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3

      - name: Installer Poppler (nécessaire pour convertir PDF → image)
        run: sudo apt-get install -y poppler-utils

      - name: Installer les dépendances Python
        run: pip install -r requirements.txt

      - name: Lancer le script Python de mise à jour
        run: python public/update_vigilance.py

      - name: Vérifier si l’image est bien créée
        run: |
          if [ -f public/vigilance.jpg ]; then
            echo "✅ Fichier image généré"
          else
            echo "❌ Le fichier vigilance.jpg n’a pas été trouvé."
            exit 1
          fi

            - name: Commit si fichier modifié
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

          if [ -f public/vigilance.jpg ]; then
            git add public/vigilance.jpg
            if ! git diff --cached --quiet; then
              git commit -m "Mise à jour vigilance automatique"
              git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }}.git
            else
              echo "✅ Aucune modification à committer"
            fi
          else
            echo "❌ Fichier vigilance.jpg non trouvé. Aucun commit effectué."
