name: Mise à jour Vigilance Réunion

on:
  schedule:
    - cron: '0 6 * * *'  # Tous les jours à 6h UTC (10h à La Réunion)
  workflow_dispatch:

jobs:
  update_vigilance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Installer Poppler (nécessaire pour convertir PDF → image)
        run: sudo apt-get install -y poppler-utils

      - name: Installer les dépendances Python
        run: pip install -r requirements.txt

      - name: Lancer le script Python de mise à jour
        run: python public/update_vigilance.py

      - name: Commit si fichier modifié
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add public/vigilance.jpg
          git diff --cached --quiet || (git commit -m "Mise à jour vigilance automatique" && git push)
- name: Commit si fichier modifié
  run: |
    git config --global user.name 'github-actions'
    git config --global user.email 'github-actions@github.com'

    if [ -f public/vigilance.jpg ]; then
      git add public/vigilance.jpg
      git diff --cached --quiet || git commit -m "Mise à jour vigilance automatique"
      git push
    else
      echo "Fichier vigilance.jpg non trouvé. Aucun commit effectué."
    fi
